export const GET_LOL_SERIES_REQUEST = "GET_LOL_SERIES_REQUEST";
export const GET_LOL_SERIES_SUCCESS = "GET_LOL_SERIES_SUCCESS";
export const GET_LOL_SERIES_FAILURE = "GET_LOL_SERIES_FAILURE";

export const SELECT_LOL_SERIES = "SELECT_LOL_SERIES";

export const GET_LOL_SERIES_TOURNAMENTS_REQUEST =
  "GET_LOL_SERIES_TOURNAMENTS_REQUEST";
export const GET_LOL_SERIES_TOURNAMENTS_SUCCESS =
  "GET_LOL_SERIES_TOURNAMENTS_SUCCESS";
export const GET_LOL_SERIES_TOURNAMENTS_FAILURE =
  "GET_LOL_SERIES_TOURNAMENTS_FAILURE";

export const GET_LOL_TOURNAMENTS_REQUEST = 'GET_LOL_TOURNAMENTS_REQUEST';
export const GET_LOL_TOURNAMENTS_SUCCESS = 'GET_LOL_TOURNAMENTS_SUCCESS';
export const GET_LOL_TOURNAMENTS_FAILURE = 'GET_LOL_TOURNAMENTS_FAILURE';

export const GET_LOL_TOURNAMENT_MATCHES_REQUEST = 'GET_LOL_TOURNAMENT_MATCHES_REQUEST';
export const GET_LOL_TOURNAMENT_MATCHES_SUCCESS = 'GET_LOL_TOURNAMENT_MATCHES_SUCCESS';
export const GET_LOL_TOURNAMENT_MATCHES_FAILURE = 'GET_LOL_TOURNAMENT_MATCHES_FAILURE';
export const CLEAR_LOL_TOURNAMENT_MATCHES = 'CLEAR_LOL_TOURNAMENT_MATCHES';

export const GET_LOL_MATCHES_REQUEST = 'GET_LOL_MATCHES_REQUEST';
export const GET_LOL_MATCHES_SUCCESS = 'GET_LOL_MATCHES_SUCCESS';
export const GET_LOL_MATCHES_FAILURE = 'GET_LOL_MATCHES_FAILURE';

export const GET_LOL_TEAMS_REQUEST = 'GET_LOL_TEAMS_REQUEST';
export const GET_LOL_TEAMS_SUCCESS = 'GET_LOL_TEAMS_SUCCESS';
export const GET_LOL_TEAMS_FAILURE = 'GET_LOL_TEAMS_FAILURE';
