export const GET_EPL_SCHEDULE_REQUEST = 'GET_EPL_SCHEDULE_REQUEST';
export const GET_EPL_SCHEDULE_SUCCESS = 'GET_EPL_SCHEDULE_SUCCESS';
export const GET_EPL_SCHEDULE_FAILURE = 'GET_EPL_SCHEDULE_FAILURE';

export const GET_EPL_TEAMS_REQUEST = 'GET_EPL_TEAMS_REQUEST';
export const GET_EPL_TEAMS_SUCCESS = 'GET_EPL_TEAMS_SUCCESS';
export const GET_EPL_TEAMS_FAILURE = 'GET_EPL_TEAMS_FAILURE';

export const GET_EPL_VIDEOS_REQUEST = 'GET_EPL_VIDEOS_REQUEST';
export const GET_EPL_VIDEOS_SUCCESS = 'GET_EPL_VIDEOS_SUCCESS';
export const GET_EPL_VIDEOS_FAILURE = 'GET_EPL_VIDEOS_FAILURE';