export const GET_TENNIS_TOURNAMENTS_REQUEST = 'GET_TENNIS_TOURNAMENTS_REQUEST';
export const GET_TENNIS_TOURNAMENTS_SUCCESS = 'GET_TENNIS_TOURNAMENTS_SUCCESS';
export const GET_TENNIS_TOURNAMENTS_FAILURE = 'GET_TENNIS_TOURNAMENTS_FAILURE';

export const GET_TENNIS_TOURNAMENT_SCHEDULE_REQUEST = 'GET_TENNIS_TOURNAMENT_SCHEDULE_REQUEST';
export const GET_TENNIS_TOURNAMENT_SCHEDULE_SUCCESS = 'GET_TENNIS_TOURNAMENT_SCHEDULE_SUCCESS';
export const GET_TENNIS_TOURNAMENT_SCHEDULE_FAILURE = 'GET_TENNIS_TOURNAMENT_SCHEDULE_FAILURE';

export const GET_TENNIS_TOURNAMENT_INFO_REQUEST = 'GET_TENNIS_TOURNAMENT_INFO_REQUEST';
export const GET_TENNIS_TOURNAMENT_INFO_SUCCESS = 'GET_TENNIS_TOURNAMENT_INFO_SUCCESS';
export const GET_TENNIS_TOURNAMENT_INFO_FAILURE = 'GET_TENNIS_TOURNAMENT_INFO_FAILURE';

export const CLEAR_TENNIS_TOURNAMENT_SCHEDULE = 'CLEAR_TENNIS_TOURNAMENT_SCHEDULE';
export const CLEAR_TENNIS_TOURNAMENT_INFO = 'CLEAR_TENNIS_TOURNAMENT_INFO';

export const GET_TENNIS_VIDEOS_REQUEST = 'GET_TENNIS_VIDEOS_REQUEST';
export const GET_TENNIS_VIDEOS_SUCCESS = 'GET_TENNIS_VIDEOS_SUCCESS';
export const GET_TENNIS_VIDEOS_FAILURE = 'GET_TENNIS_VIDEOS_FAILURE';
