export const GET_EVENTS_REQUEST = 'GET_EVENTS_REQUEST';
export const GET_EVENTS_SUCCESS = 'GET_EVENTS_SUCCESS';
export const GET_EVENTS_FAILURE = 'GET_EVENTS_FAILURE';

export const GET_EVENTS_FOR_WEEK_REQUEST = 'GET_EVENTS_FOR_WEEK_REQUEST';
export const GET_EVENTS_FOR_WEEK_SUCCESS = 'GET_EVENTS_FOR_WEEK_SUCCESS';
export const GET_EVENTS_FOR_WEEK_FAILURE = 'GET_EVENTS_FOR_WEEK_FAILURE';
