export const GET_OVERWATCH_TOURNAMENTS_REQUEST = 'GET_OVERWATCH_TOURNAMENTS_REQUEST';
export const GET_OVERWATCH_TOURNAMENTS_SUCCESS = 'GET_OVERWATCH_TOURNAMENTS_SUCCESS';
export const GET_OVERWATCH_TOURNAMENTS_FAILURE = 'GET_OVERWATCH_TOURNAMENTS_FAILURE';

export const GET_OVERWATCH_TOURNAMENT_MATCHES_REQUEST = 'GET_OVERWATCH_TOURNAMENT_MATCHES_REQUEST';
export const GET_OVERWATCH_TOURNAMENT_MATCHES_SUCCESS = 'GET_OVERWATCH_TOURNAMENT_MATCHES_SUCCESS';
export const GET_OVERWATCH_TOURNAMENT_MATCHES_FAILURE = 'GET_OVERWATCH_TOURNAMENT_MATCHES_FAILURE';
export const CLEAR_OVERWATCH_TOURNAMENT_MATCHES = 'CLEAR_OVERWATCH_TOURNAMENT_MATCHES';

export const GET_OVERWATCH_MATCHES_REQUEST = 'GET_OVERWATCH_MATCHES_REQUEST';
export const GET_OVERWATCH_MATCHES_SUCCESS = 'GET_OVERWATCH_MATCHES_SUCCESS';
export const GET_OVERWATCH_MATCHES_FAILURE = 'GET_OVERWATCH_MATCHES_FAILURE';