export const GET_DOTA_TOURNAMENTS_REQUEST = "GET_DOTA_TOURNAMENTS_REQUEST";
export const GET_DOTA_TOURNAMENTS_SUCCESS = "GET_DOTA_TOURNAMENTS_SUCCESS";
export const GET_DOTA_TOURNAMENTS_FAILURE = "GET_DOTA_TOURNAMENTS_FAILURE";

export const GET_DOTA_TOURNAMENT_MATCHES_REQUEST =
  "GET_DOTA_TOURNAMENT_MATCHES_REQUEST";
export const GET_DOTA_TOURNAMENT_MATCHES_SUCCESS =
  "GET_DOTA_TOURNAMENT_MATCHES_SUCCESS";
export const GET_DOTA_TOURNAMENT_MATCHES_FAILURE =
  "GET_DOTA_TOURNAMENT_MATCHES_FAILURE";
export const CLEAR_DOTA_TOURNAMENT_MATCHES = "CLEAR_DOTA_TOURNAMENT_MATCHES";

export const GET_DOTA_TEAMS_REQUEST = "GET_DOTA_TEAMS_REQUEST";
export const GET_DOTA_TEAMS_SUCCESS = "GET_DOTA_TEAMS_SUCCESS";
export const GET_DOTA_TEAMS_FAILURE = "GET_DOTA_TEAMS_FAILURE";

export const GET_DOTA_SERIES_REQUEST = "GET_DOTA_SERIES_REQUEST";
export const GET_DOTA_SERIES_SUCCESS = "GET_DOTA_SERIES_SUCCESS";
export const GET_DOTA_SERIES_FAILURE = "GET_DOTA_SERIES_FAILURE";

export const GET_DOTA_MATCHES_REQUEST = "GET_DOTA_MATCHES_REQUEST";
export const GET_DOTA_MATCHES_SUCCESS = "GET_DOTA_MATCHES_SUCCESS";
export const GET_DOTA_MATCHES_FAILURE = "GET_DOTA_MATCHES_FAILURE";

export const GET_DOTA_VIDEOS_REQUEST = "GET_DOTA_VIDEOS_REQUEST";
export const GET_DOTA_VIDEOS_SUCCESS = "GET_DOTA_VIDEOS_SUCCESS";
export const GET_DOTA_VIDEOS_FAILURE = "GET_DOTA_VIDEOS_FAILURE";

export const SELECT_DOTA_SERIES = "SELECT_DOTA_SERIES";

export const GET_DOTA_SERIES_TOURNAMENTS_REQUEST =
  "GET_DOTA_SERIES_TOURNAMENTS_REQUEST";
export const GET_DOTA_SERIES_TOURNAMENTS_SUCCESS =
  "GET_DOTA_SERIES_TOURNAMENTS_SUCCESS";
export const GET_DOTA_SERIES_TOURNAMENTS_FAILURE =
  "GET_DOTA_SERIES_TOURNAMENTS_FAILURE";
