export const dotaActions = {
  GET_DOTA_DATA: 'GET_DOTA_DATA',
  GET_DOTA_LEAGUES_REQUEST: 'GET_DOTA_LEAGUES_REQUEST',
  GET_DOTA_LEAGUES_SUCCESS: 'GET_DOTA_LEAGUES_SUCCESS',
  GET_DOTA_LEAGUES_FAILURE: 'GET_DOTA_LEAGUES_FAILURE',
  GET_DOTA_PRO_MATCHES_REQUEST: 'GET_DOTA_PRO_MATCHES_REQUEST',
  GET_DOTA_PRO_MATCHES_SUCCESS: 'GET_DOTA_PRO_MATCHES_SUCCESS',
  GET_DOTA_PRO_MATCHES_FAILURE: 'GET_DOTA_PRO_MATCHES_FAILURE',
  GET_DOTA_TEAMS_REQUEST: 'GET_DOTA_TEAMS_REQUEST',
  GET_DOTA_TEAMS_SUCCESS: 'GET_DOTA_TEAMS_SUCCESS',
  GET_DOTA_TEAMS_FAILURE: 'GET_DOTA_TEAMS_FAILURE',
};
