import { createActionStringObjects } from '../../../helpers/utils';

export const GET_NBA_SCHEDULE_REQUEST = 'GET_NBA_SCHEDULE_REQUEST';
export const GET_NBA_SCHEDULE_SUCCESS = 'GET_NBA_SCHEDULE_SUCCESS';
export const GET_NBA_SCHEDULE_FAILURE = 'GET_NBA_SCHEDULE_FAILURE';
export const GET_NBA_TEAMS_REQUEST = 'GET_NBA_TEAMS_REQUEST';
export const GET_NBA_TEAMS_SUCCESS = 'GET_NBA_TEAMS_SUCCESS';
export const GET_NBA_TEAMS_FAILURE = 'GET_NBA_TEAMS_FAILURE';
export const GET_NBA_VIDEOS_REQUEST = 'GET_NBA_VIDEOS_REQUEST';
export const GET_NBA_VIDEOS_SUCCESS = 'GET_NBA_VIDEOS_SUCCESS';
export const GET_NBA_VIDEOS_FAILURE = 'GET_NBA_VIDEOS_FAILURE';

export const GET_EPL_SCHEDULE_REQUEST = 'GET_EPL_SCHEDULE_REQUEST';
export const GET_EPL_SCHEDULE_SUCCESS = 'GET_EPL_SCHEDULE_SUCCESS';
export const GET_EPL_SCHEDULE_FAILURE = 'GET_EPL_SCHEDULE_FAILURE';
export const GET_EPL_TEAMS_REQUEST = 'GET_EPL_TEAMS_REQUEST';
export const GET_EPL_TEAMS_SUCCESS = 'GET_EPL_TEAMS_SUCCESS';
export const GET_EPL_TEAMS_FAILURE = 'GET_EPL_TEAMS_FAILURE';
export const GET_EPL_VIDEOS_REQUEST = 'GET_EPL_VIDEOS_REQUEST';
export const GET_EPL_VIDEOS_SUCCESS = 'GET_EPL_VIDEOS_SUCCESS';
export const GET_EPL_VIDEOS_FAILURE = 'GET_EPL_VIDEOS_FAILURE';

export const GET_CHAMPIONS_LEAGUE_SCHEDULE_REQUEST = 'GET_CHAMPIONS_LEAGUE_SCHEDULE_REQUEST';
export const GET_CHAMPIONS_LEAGUE_SCHEDULE_SUCCESS = 'GET_CHAMPIONS_LEAGUE_SCHEDULE_SUCCESS';
export const GET_CHAMPIONS_LEAGUE_SCHEDULE_FAILURE = 'GET_CHAMPIONS_LEAGUE_SCHEDULE_FAILURE';
export const GET_CHAMPIONS_LEAGUE_TEAMS_REQUEST = 'GET_CHAMPIONS_LEAGUE_TEAMS_REQUEST';
export const GET_CHAMPIONS_LEAGUE_TEAMS_SUCCESS = 'GET_CHAMPIONS_LEAGUE_TEAMS_SUCCESS';
export const GET_CHAMPIONS_LEAGUE_TEAMS_FAILURE = 'GET_CHAMPIONS_LEAGUE_TEAMS_FAILURE';
export const GET_CHAMPIONS_LEAGUE_VIDEOS_REQUEST = 'GET_CHAMPIONS_LEAGUE_VIDEOS_REQUEST';
export const GET_CHAMPIONS_LEAGUE_VIDEOS_SUCCESS = 'GET_CHAMPIONS_LEAGUE_VIDEOS_SUCCESS';
export const GET_CHAMPIONS_LEAGUE_VIDEOS_FAILURE = 'GET_CHAMPIONS_LEAGUE_VIDEOS_FAILURE';

export const GET_EUROPA_LEAGUE_SCHEDULE_REQUEST = 'GET_EUROPA_LEAGUE_SCHEDULE_REQUEST';
export const GET_EUROPA_LEAGUE_SCHEDULE_SUCCESS = 'GET_EUROPA_LEAGUE_SCHEDULE_SUCCESS';
export const GET_EUROPA_LEAGUE_SCHEDULE_FAILURE = 'GET_EUROPA_LEAGUE_SCHEDULE_FAILURE';
export const GET_EUROPA_LEAGUE_TEAMS_REQUEST = 'GET_EUROPA_LEAGUE_TEAMS_REQUEST';
export const GET_EUROPA_LEAGUE_TEAMS_SUCCESS = 'GET_EUROPA_LEAGUE_TEAMS_SUCCESS';
export const GET_EUROPA_LEAGUE_TEAMS_FAILURE = 'GET_EUROPA_LEAGUE_TEAMS_FAILURE';
export const GET_EUROPA_LEAGUE_VIDEOS_REQUEST = 'GET_EUROPA_LEAGUE_VIDEOS_REQUEST';
export const GET_EUROPA_LEAGUE_VIDEOS_SUCCESS = 'GET_EUROPA_LEAGUE_VIDEOS_SUCCESS';
export const GET_EUROPA_LEAGUE_VIDEOS_FAILURE = 'GET_EUROPA_LEAGUE_VIDEOS_FAILURE';

export const GET_TENNIS_TOURNAMENTS_REQUEST = 'GET_TENNIS_TOURNAMENTS_REQUEST';
export const GET_TENNIS_TOURNAMENTS_SUCCESS = 'GET_TENNIS_TOURNAMENTS_SUCCESS';
export const GET_TENNIS_TOURNAMENTS_FAILURE = 'GET_TENNIS_TOURNAMENTS_FAILURE';
export const GET_TENNIS_TOURNAMENT_SCHEDULE_REQUEST = 'GET_TENNIS_TOURNAMENT_SCHEDULE_REQUEST';
export const GET_TENNIS_TOURNAMENT_SCHEDULE_SUCCESS = 'GET_TENNIS_TOURNAMENT_SCHEDULE_SUCCESS';
export const GET_TENNIS_TOURNAMENT_SCHEDULE_FAILURE = 'GET_TENNIS_TOURNAMENT_SCHEDULE_FAILURE';
export const GET_TENNIS_TOURNAMENT_INFO_REQUEST = 'GET_TENNIS_TOURNAMENT_INFO_REQUEST';
export const GET_TENNIS_TOURNAMENT_INFO_SUCCESS = 'GET_TENNIS_TOURNAMENT_INFO_SUCCESS';
export const GET_TENNIS_TOURNAMENT_INFO_FAILURE = 'GET_TENNIS_TOURNAMENT_INFO_FAILURE';
export const CLEAR_TENNIS_TOURNAMENT_SCHEDULE = 'CLEAR_TENNIS_TOURNAMENT_SCHEDULE';
export const CLEAR_TENNIS_TOURNAMENT_INFO = 'CLEAR_TENNIS_TOURNAMENT_INFO';

export const GET_DOTA_TOURNAMENTS_REQUEST = 'GET_DOTA_TOURNAMENTS_REQUEST';
export const GET_DOTA_TOURNAMENTS_SUCCESS = 'GET_DOTA_TOURNAMENTS_SUCCESS';
export const GET_DOTA_TOURNAMENTS_FAILURE = 'GET_DOTA_TOURNAMENTS_FAILURE';
export const GET_DOTA_TOURNAMENT_MATCHES_REQUEST = 'GET_DOTA_TOURNAMENT_MATCHES_REQUEST';
export const GET_DOTA_TOURNAMENT_MATCHES_SUCCESS = 'GET_DOTA_TOURNAMENT_MATCHES_SUCCESS';
export const GET_DOTA_TOURNAMENT_MATCHES_FAILURE = 'GET_DOTA_TOURNAMENT_MATCHES_FAILURE';
export const CLEAR_DOTA_TOURNAMENT_MATCHES = 'CLEAR_DOTA_TOURNAMENT_MATCHES';
export const GET_DOTA_TEAMS_REQUEST = 'GET_DOTA_TEAMS_REQUEST';
export const GET_DOTA_TEAMS_SUCCESS = 'GET_DOTA_TEAMS_SUCCESS';
export const GET_DOTA_TEAMS_FAILURE = 'GET_DOTA_TEAMS_FAILURE';
export const GET_DOTA_SERIES_REQUEST = 'GET_DOTA_SERIES_REQUEST';
export const GET_DOTA_SERIES_SUCCESS = 'GET_DOTA_SERIES_SUCCESS';
export const GET_DOTA_SERIES_FAILURE = 'GET_DOTA_SERIES_FAILURE';
export const GET_DOTA_MATCHES_REQUEST = 'GET_DOTA_MATCHES_REQUEST';
export const GET_DOTA_MATCHES_SUCCESS = 'GET_DOTA_MATCHES_SUCCESS';
export const GET_DOTA_MATCHES_FAILURE = 'GET_DOTA_MATCHES_FAILURE';
export const GET_DOTA_VIDEOS_REQUEST = 'GET_DOTA_VIDEOS_REQUEST';
export const GET_DOTA_VIDEOS_SUCCESS = 'GET_DOTA_VIDEOS_SUCCESS';
export const GET_DOTA_VIDEOS_FAILURE = 'GET_DOTA_VIDEOS_FAILURE';

export const GET_LOL_TOURNAMENTS_REQUEST = 'GET_LOL_TOURNAMENTS_REQUEST';
export const GET_LOL_TOURNAMENTS_SUCCESS = 'GET_LOL_TOURNAMENTS_SUCCESS';
export const GET_LOL_TOURNAMENTS_FAILURE = 'GET_LOL_TOURNAMENTS_FAILURE';
export const GET_LOL_TOURNAMENT_MATCHES_REQUEST = 'GET_LOL_TOURNAMENT_MATCHES_REQUEST';
export const GET_LOL_TOURNAMENT_MATCHES_SUCCESS = 'GET_LOL_TOURNAMENT_MATCHES_SUCCESS';
export const GET_LOL_TOURNAMENT_MATCHES_FAILURE = 'GET_LOL_TOURNAMENT_MATCHES_FAILURE';
export const CLEAR_LOL_TOURNAMENT_MATCHES = 'CLEAR_LOL_TOURNAMENT_MATCHES';
export const GET_LOL_MATCHES_REQUEST = 'GET_LOL_MATCHES_REQUEST';
export const GET_LOL_MATCHES_SUCCESS = 'GET_LOL_MATCHES_SUCCESS';
export const GET_LOL_MATCHES_FAILURE = 'GET_LOL_MATCHES_FAILURE';
export const GET_LOL_TEAMS_REQUEST = 'GET_LOL_TEAMS_REQUEST';
export const GET_LOL_TEAMS_SUCCESS = 'GET_LOL_TEAMS_SUCCESS';
export const GET_LOL_TEAMS_FAILURE = 'GET_LOL_TEAMS_FAILURE';
export const GET_LOL_VIDEOS_REQUEST = 'GET_LOL_VIDEOS_REQUEST';
export const GET_LOL_VIDEOS_SUCCESS = 'GET_LOL_VIDEOS_SUCCESS';
export const GET_LOL_VIDEOS_FAILURE = 'GET_LOL_VIDEOS_FAILURE';

export const nbaActions = createActionStringObjects([
  'GET_NBA_SCHEDULE_REQUEST',
  'GET_NBA_SCHEDULE_SUCCESS',
  'GET_NBA_SCHEDULE_FAILURE',
  'GET_NBA_TEAMS_REQUEST',
  'GET_NBA_TEAMS_SUCCESS',
  'GET_NBA_TEAMS_FAILURE',
  'GET_NBA_VIDEOS_REQUEST',
  'GET_NBA_VIDEOS_SUCCESS',
  'GET_NBA_VIDEOS_FAILURE'
]);

export const eplActions = createActionStringObjects([
  'GET_EPL_SCHEDULE_REQUEST',
  'GET_EPL_SCHEDULE_SUCCESS',
  'GET_EPL_SCHEDULE_FAILURE',
  'GET_EPL_TEAMS_REQUEST',
  'GET_EPL_TEAMS_SUCCESS',
  'GET_EPL_TEAMS_FAILURE',
  'GET_EPL_VIDEOS_REQUEST',
  'GET_EPL_VIDEOS_SUCCESS',
  'GET_EPL_VIDEOS_FAILURE'
]);

export const championsLeagueActions = createActionStringObjects([
  'GET_CHAMPIONS_LEAGUE_SCHEDULE_REQUEST',
  'GET_CHAMPIONS_LEAGUE_SCHEDULE_SUCCESS',
  'GET_CHAMPIONS_LEAGUE_SCHEDULE_FAILURE',
  'GET_CHAMPIONS_LEAGUE_TEAMS_REQUEST',
  'GET_CHAMPIONS_LEAGUE_TEAMS_SUCCESS',
  'GET_CHAMPIONS_LEAGUE_TEAMS_FAILURE',
  'GET_CHAMPIONS_LEAGUE_VIDEOS_REQUEST',
  'GET_CHAMPIONS_LEAGUE_VIDEOS_SUCCESS',
  'GET_CHAMPIONS_LEAGUE_VIDEOS_FAILURE'
]);

export const europaLeagueActions = createActionStringObjects([
  'GET_EUROPA_LEAGUE_SCHEDULE_REQUEST',
  'GET_EUROPA_LEAGUE_SCHEDULE_SUCCESS',
  'GET_EUROPA_LEAGUE_SCHEDULE_FAILURE',
  'GET_EUROPA_LEAGUE_TEAMS_REQUEST',
  'GET_EUROPA_LEAGUE_TEAMS_SUCCESS',
  'GET_EUROPA_LEAGUE_TEAMS_FAILURE',
  'GET_EUROPA_LEAGUE_VIDEOS_REQUEST',
  'GET_EUROPA_LEAGUE_VIDEOS_SUCCESS',
  'GET_EUROPA_LEAGUE_VIDEOS_FAILURE'
]);

export const tennisActions = createActionStringObjects([
  'GET_TENNIS_TOURNAMENTS_REQUEST',
  'GET_TENNIS_TOURNAMENTS_SUCCESS',
  'GET_TENNIS_TOURNAMENTS_FAILURE',
  'GET_TENNIS_TOURNAMENT_SCHEDULE_REQUEST',
  'GET_TENNIS_TOURNAMENT_SCHEDULE_SUCCESS',
  'GET_TENNIS_TOURNAMENT_SCHEDULE_FAILURE',
  'GET_TENNIS_TOURNAMENT_INFO_REQUEST',
  'GET_TENNIS_TOURNAMENT_INFO_SUCCESS',
  'GET_TENNIS_TOURNAMENT_INFO_FAILURE',
  'CLEAR_TENNIS_TOURNAMENT_SCHEDULE',
  'CLEAR_TENNIS_TOURNAMENT_INFO'
]);

export const dotaActions = createActionStringObjects([
  'GET_DOTA_TOURNAMENTS_REQUEST',
  'GET_DOTA_TOURNAMENTS_SUCCESS',
  'GET_DOTA_TOURNAMENTS_FAILURE',
  'GET_DOTA_TOURNAMENT_MATCHES_REQUEST',
  'GET_DOTA_TOURNAMENT_MATCHES_SUCCESS',
  'GET_DOTA_TOURNAMENT_MATCHES_FAILURE',
  'CLEAR_DOTA_TOURNAMENT_MATCHES',
  'GET_DOTA_TEAMS_REQUEST',
  'GET_DOTA_TEAMS_SUCCESS',
  'GET_DOTA_TEAMS_FAILURE',
  'GET_DOTA_SERIES_REQUEST',
  'GET_DOTA_SERIES_SUCCESS',
  'GET_DOTA_SERIES_FAILURE',
  'GET_DOTA_MATCHES_REQUEST',
  'GET_DOTA_MATCHES_SUCCESS',
  'GET_DOTA_MATCHES_FAILURE',
  'GET_DOTA_VIDEOS_REQUEST',
  'GET_DOTA_VIDEOS_SUCCESS',
  'GET_DOTA_VIDEOS_FAILURE'
]);

export const lolActions = createActionStringObjects([
  'GET_LOL_TOURNAMENTS_REQUEST',
  'GET_LOL_TOURNAMENTS_SUCCESS',
  'GET_LOL_TOURNAMENTS_FAILURE',
  'GET_LOL_TOURNAMENT_MATCHES_REQUEST',
  'GET_LOL_TOURNAMENT_MATCHES_SUCCESS',
  'GET_LOL_TOURNAMENT_MATCHES_FAILURE',
  'CLEAR_LOL_TOURNAMENT_MATCHES',
  'GET_LOL_MATCHES_REQUEST',
  'GET_LOL_MATCHES_SUCCESS',
  'GET_LOL_MATCHES_FAILURE',
  'GET_LOL_TEAMS_REQUEST',
  'GET_LOL_TEAMS_SUCCESS',
  'GET_LOL_TEAMS_FAILURE',
  'GET_LOL_VIDEOS_REQUEST',
  'GET_LOL_VIDEOS_SUCCESS',
  'GET_LOL_VIDEOS_FAILURE'
]);
