export const GET_CSGO_TOURNAMENTS_REQUEST = 'GET_CSGO_TOURNAMENTS_REQUEST';
export const GET_CSGO_TOURNAMENTS_SUCCESS = 'GET_CSGO_TOURNAMENTS_SUCCESS';
export const GET_CSGO_TOURNAMENTS_FAILURE = 'GET_CSGO_TOURNAMENTS_FAILURE';

export const GET_CSGO_TOURNAMENT_MATCHES_REQUEST = 'GET_CSGO_TOURNAMENT_MATCHES_REQUEST';
export const GET_CSGO_TOURNAMENT_MATCHES_SUCCESS = 'GET_CSGO_TOURNAMENT_MATCHES_SUCCESS';
export const GET_CSGO_TOURNAMENT_MATCHES_FAILURE = 'GET_CSGO_TOURNAMENT_MATCHES_FAILURE';
export const CLEAR_CSGO_TOURNAMENT_MATCHES = 'CLEAR_CSGO_TOURNAMENT_MATCHES';

export const GET_CSGO_MATCHES_REQUEST = 'GET_CSGO_MATCHES_REQUEST';
export const GET_CSGO_MATCHES_SUCCESS = 'GET_CSGO_MATCHES_SUCCESS';
export const GET_CSGO_MATCHES_FAILURE = 'GET_CSGO_MATCHES_FAILURE';

// export const GET_CSGO_TEAMS_REQUEST = 'GET_CSGO_TEAMS_REQUEST';
// export const GET_CSGO_TEAMS_SUCCESS = 'GET_CSGO_TEAMS_SUCCESS';
// export const GET_CSGO_TEAMS_FAILURE = 'GET_CSGO_TEAMS_FAILURE';

// export const GET_CSGO_SERIES_REQUEST = 'GET_CSGO_SERIES_REQUEST';
// export const GET_CSGO_SERIES_SUCCESS = 'GET_CSGO_SERIES_SUCCESS';
// export const GET_CSGO_SERIES_FAILURE = 'GET_CSGO_SERIES_FAILURE';
